name: niral_prj
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  animated_splash_screen: ^1.3.0
  image_picker: ^1.1.2
  icons_plus: ^5.0.0
  shared_preferences: ^2.5.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.8.4
  # provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your asset directories here, uncomment the ones you need:
  assets:
    - assets/
    - assets/mango/
    - assets/lemon/
    - assets/wheat/

  # Optional: Add fonts if needed for your app
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
